name: employee_updates_app
description: A Flutter web and mobile app for employee updates with roles and Firebase integration.

publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.1.0
  provider: ^6.0.5
  flutter_hooks: ^0.21.2
  intl: ^0.18.1
  flutterfire_cli: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
